// Third-party library configurations (e.g., i18n, logger, analytics).
// Each library gets its own file: lib/i18n.ts, lib/logger.ts, etc.

// shadcn/ui utility function lives at lib/utils.ts (generated by shadcn init).
// Re-export it here for convenience:
export { cn } from './utils'
